### ISSUE TITLE
Define roadmap for first stable release

### ISSUE THREAD

**Issue by markmercedes** [markmercedes/krudmin#50]
- [ ] DateTime field
- [ ] Email Field
- [ ] Belongs to Link for relations in show page
- [ ] Layout API
- [ ] Spanish Translations
- [ ] Stand Alone controllers that don't depend on having a resource manager but are able to display content using the app template
- [ ] Generators
- [ ] Code Documentation
- [ ] Wiki
- [ ] Publish Gem
- [ ] Deploy Sample App
- [ ] Promote project in ruby toolbox, etc..
